In [50]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.linear_model import LinearRegression

In [140]:
csvfile = "cleandata5.csv"
data = pd.read_csv(csvfile)

In [141]:
data["ID"].size

119274

In [114]:
x = data[["Lift_retail"]]
y = data["Lift_DOD"].values.reshape(-1,1)

In [115]:
# Split the data into training and testing

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, random_state=42)


In [116]:
from sklearn.preprocessing import StandardScaler

# Create a StandardScater model and fit it to the training data

X_scaler = StandardScaler().fit(X_train)
y_scaler = StandardScaler().fit(y_train)


In [117]:
# Transform the training and testing data using the X_scaler and y_scaler models

X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)
y_train_scaled = y_scaler.transform(y_train)
y_test_scaled = y_scaler.transform(y_test)


In [135]:
# n_samples = data["size"].size
# n_features = 3
# x = data[["AUR TY", "size", "WM Week #"]]
# y = data["Units"]
# #y = data["Units"].values.reshape(-1, 1)


model = KNeighborsRegressor(n_neighbors=20)

# try SGD regressor
# model = linear_model.SGDRegressor()
model.fit(X_train_scaled, y_train_scaled)

# # try nearest
# from sklearn.neighbors import NearestNeighbors


KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
          metric_params=None, n_jobs=1, n_neighbors=20, p=2,
          weights='uniform')

In [136]:
predictions = model.predict(X_test_scaled)
# pd.DataFrame({"Predicted": [predictions], "Actual": [y_test_scaled], "Error": [predictions - y_test_scaled]}, index=True)[["Predicted", "Actual", "Error"]] 

pd.DataFrame({"P":[predictions], "Y":[y_test_scaled]})
# print(predictions)

P  \
0  [[-0.104331868654], [-0.104331868654], [-0.104...   

                                                   Y  
0  [[2.48164885016], [-0.116969852592], [0.171765...

In [137]:
print(predictions)

[[-0.10433187]
 [-0.10433187]
 [-0.10433187]
 ..., 
 [ 0.26262659]
 [ 0.09391631]
 [-0.10433187]]


In [138]:
print(y_test_scaled)

[[ 2.48164885]
 [-0.11696985]
 [ 0.17176556]
 ..., 
 [ 0.46050097]
 [ 1.3267072 ]
 [-5.89167808]]


Notes from prev test

In [139]:
score = model.score(X_test_scaled, y_test_scaled)
print(f"R2 Score: {score}")

R2 Score: 0.0183072379273701


In [38]:
predictions = KNeighborsRegressor(...)
print(model.predict([[32, 109, .2]]))
# pd.DataFrame({"Predicted": predictions, "Actual": y, "Error": predictions - y})[["Predicted", "Actual", "Error"]]

[[ 1309.]]


In [53]:
score = model.score(X_test, y_test)
print(f"R2 Score: {score}")

R2 Score: -0.21547478937454811


In [40]:
from sklearn import metrics
print(metrics.mean_squared_error)

<function mean_squared_error at 0x1a14e3b8c8>


In [80]:
weekly_sales = []
for weeks in range (1,13):
    forecast = model.predict([[32, 2017, weeks, 105, 55427159]])
    weekly_sales.append(forecast)
weekly_sales

[array([[ 501.]]),
 array([[ 501.]]),
 array([[ 501.]]),
 array([[ 501.]]),
 array([[ 501.]]),
 array([[ 849.]]),
 array([[ 849.]]),
 array([[ 935.5]]),
 array([[ 935.5]]),
 array([[ 935.5]]),
 array([[ 935.5]]),
 array([[ 935.5]])]